// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package cloudfront

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	endpoints_sdkv1 "github.com/aws/aws-sdk-go/aws/endpoints"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	cloudfront_sdkv1 "github.com/aws/aws-sdk-go/service/cloudfront"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
	"log"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{
		{
			Factory: newResourceContinuousDeploymentPolicy,
			Name:    "Continuous Deployment Policy",
		},
	}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
		{
			Factory:  DataSourceCachePolicy,
			TypeName: "aws_cloudfront_cache_policy",
		},
		{
			Factory:  DataSourceDistribution,
			TypeName: "aws_cloudfront_distribution",
		},
		{
			Factory:  DataSourceFunction,
			TypeName: "aws_cloudfront_function",
		},
		{
			Factory:  DataSourceLogDeliveryCanonicalUserID,
			TypeName: "aws_cloudfront_log_delivery_canonical_user_id",
		},
		{
			Factory:  DataSourceOriginAccessIdentities,
			TypeName: "aws_cloudfront_origin_access_identities",
		},
		{
			Factory:  DataSourceOriginAccessIdentity,
			TypeName: "aws_cloudfront_origin_access_identity",
		},
		{
			Factory:  DataSourceOriginRequestPolicy,
			TypeName: "aws_cloudfront_origin_request_policy",
		},
		{
			Factory:  DataSourceRealtimeLogConfig,
			TypeName: "aws_cloudfront_realtime_log_config",
		},
		{
			Factory:  DataSourceResponseHeadersPolicy,
			TypeName: "aws_cloudfront_response_headers_policy",
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceCachePolicy,
			TypeName: "aws_cloudfront_cache_policy",
		},
		{
			Factory:  ResourceDistribution,
			TypeName: "aws_cloudfront_distribution",
			Name:     "Distribution",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceFieldLevelEncryptionConfig,
			TypeName: "aws_cloudfront_field_level_encryption_config",
		},
		{
			Factory:  ResourceFieldLevelEncryptionProfile,
			TypeName: "aws_cloudfront_field_level_encryption_profile",
		},
		{
			Factory:  ResourceFunction,
			TypeName: "aws_cloudfront_function",
		},
		{
			Factory:  ResourceKeyGroup,
			TypeName: "aws_cloudfront_key_group",
		},
		{
			Factory:  ResourceMonitoringSubscription,
			TypeName: "aws_cloudfront_monitoring_subscription",
		},
		{
			Factory:  ResourceOriginAccessControl,
			TypeName: "aws_cloudfront_origin_access_control",
		},
		{
			Factory:  ResourceOriginAccessIdentity,
			TypeName: "aws_cloudfront_origin_access_identity",
		},
		{
			Factory:  ResourceOriginRequestPolicy,
			TypeName: "aws_cloudfront_origin_request_policy",
		},
		{
			Factory:  ResourcePublicKey,
			TypeName: "aws_cloudfront_public_key",
		},
		{
			Factory:  ResourceRealtimeLogConfig,
			TypeName: "aws_cloudfront_realtime_log_config",
		},
		{
			Factory:  ResourceResponseHeadersPolicy,
			TypeName: "aws_cloudfront_response_headers_policy",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.CloudFront
}

// NewConn returns a new AWS SDK for Go v1 client for this service package's AWS API.
func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*cloudfront_sdkv1.CloudFront, error) {
	sess := config["session"].(*session_sdkv1.Session)

	if endpoint := config["endpoint"].(string); endpoint != "" && sess.Config.UseFIPSEndpoint == endpoints_sdkv1.FIPSEndpointStateEnabled {
		// The SDK doesn't allow setting a custom non-FIPS endpoint *and* enabling UseFIPSEndpoint.
		// However there are a few cases where this is necessary; some services don't have FIPS endpoints,
		// and for some services (e.g. CloudFront) the SDK generates the wrong fips endpoint.
		// While forcing this to disabled may result in the end-user not using a FIPS endpoint as specified
		// by setting UseFIPSEndpoint=true in the provider, the user also explicitly changed the endpoint, so
		// here we need to assume the user knows what they're doing.
		log.Printf("[WARN] UseFIPSEndpoint is enabled but a custom endpoint (%s) is configured, ignoring UseFIPSEndpoint.", endpoint)
		sess.Config.UseFIPSEndpoint = endpoints_sdkv1.FIPSEndpointStateDisabled
	}

	return cloudfront_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
