// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package autoscaling

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	endpoints_sdkv1 "github.com/aws/aws-sdk-go/aws/endpoints"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	autoscaling_sdkv1 "github.com/aws/aws-sdk-go/service/autoscaling"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
	"log"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
		{
			Factory:  DataSourceGroup,
			TypeName: "aws_autoscaling_group",
		},
		{
			Factory:  DataSourceGroups,
			TypeName: "aws_autoscaling_groups",
		},
		{
			Factory:  DataSourceLaunchConfiguration,
			TypeName: "aws_launch_configuration",
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceAttachment,
			TypeName: "aws_autoscaling_attachment",
		},
		{
			Factory:  ResourceGroup,
			TypeName: "aws_autoscaling_group",
		},
		{
			Factory:  ResourceGroupTag,
			TypeName: "aws_autoscaling_group_tag",
		},
		{
			Factory:  ResourceLifecycleHook,
			TypeName: "aws_autoscaling_lifecycle_hook",
		},
		{
			Factory:  ResourceNotification,
			TypeName: "aws_autoscaling_notification",
		},
		{
			Factory:  ResourcePolicy,
			TypeName: "aws_autoscaling_policy",
		},
		{
			Factory:  ResourceSchedule,
			TypeName: "aws_autoscaling_schedule",
		},
		{
			Factory:  ResourceTrafficSourceAttachment,
			TypeName: "aws_autoscaling_traffic_source_attachment",
		},
		{
			Factory:  ResourceLaunchConfiguration,
			TypeName: "aws_launch_configuration",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.AutoScaling
}

// NewConn returns a new AWS SDK for Go v1 client for this service package's AWS API.
func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*autoscaling_sdkv1.AutoScaling, error) {
	sess := config["session"].(*session_sdkv1.Session)

	if endpoint := config["endpoint"].(string); endpoint != "" && sess.Config.UseFIPSEndpoint == endpoints_sdkv1.FIPSEndpointStateEnabled {
		// The SDK doesn't allow setting a custom non-FIPS endpoint *and* enabling UseFIPSEndpoint.
		// However there are a few cases where this is necessary; some services don't have FIPS endpoints,
		// and for some services (e.g. CloudFront) the SDK generates the wrong fips endpoint.
		// While forcing this to disabled may result in the end-user not using a FIPS endpoint as specified
		// by setting UseFIPSEndpoint=true in the provider, the user also explicitly changed the endpoint, so
		// here we need to assume the user knows what they're doing.
		log.Printf("[WARN] UseFIPSEndpoint is enabled but a custom endpoint (%s) is configured, ignoring UseFIPSEndpoint.", endpoint)
		sess.Config.UseFIPSEndpoint = endpoints_sdkv1.FIPSEndpointStateDisabled
	}

	return autoscaling_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
