// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package kms

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	endpoints_sdkv1 "github.com/aws/aws-sdk-go/aws/endpoints"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	kms_sdkv1 "github.com/aws/aws-sdk-go/service/kms"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
	"log"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
		{
			Factory:  DataSourceAlias,
			TypeName: "aws_kms_alias",
		},
		{
			Factory:  DataSourceCiphertext,
			TypeName: "aws_kms_ciphertext",
		},
		{
			Factory:  DataSourceCustomKeyStore,
			TypeName: "aws_kms_custom_key_store",
		},
		{
			Factory:  DataSourceKey,
			TypeName: "aws_kms_key",
		},
		{
			Factory:  DataSourcePublicKey,
			TypeName: "aws_kms_public_key",
		},
		{
			Factory:  DataSourceSecret,
			TypeName: "aws_kms_secret",
		},
		{
			Factory:  DataSourceSecrets,
			TypeName: "aws_kms_secrets",
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceAlias,
			TypeName: "aws_kms_alias",
		},
		{
			Factory:  ResourceCiphertext,
			TypeName: "aws_kms_ciphertext",
		},
		{
			Factory:  ResourceCustomKeyStore,
			TypeName: "aws_kms_custom_key_store",
		},
		{
			Factory:  ResourceExternalKey,
			TypeName: "aws_kms_external_key",
			Name:     "External Key",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  ResourceGrant,
			TypeName: "aws_kms_grant",
		},
		{
			Factory:  ResourceKey,
			TypeName: "aws_kms_key",
			Name:     "Key",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  ResourceKeyPolicy,
			TypeName: "aws_kms_key_policy",
		},
		{
			Factory:  ResourceReplicaExternalKey,
			TypeName: "aws_kms_replica_external_key",
			Name:     "Replica External Key",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  ResourceReplicaKey,
			TypeName: "aws_kms_replica_key",
			Name:     "Replica Key",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.KMS
}

// NewConn returns a new AWS SDK for Go v1 client for this service package's AWS API.
func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*kms_sdkv1.KMS, error) {
	sess := config["session"].(*session_sdkv1.Session)

	if endpoint := config["endpoint"].(string); endpoint != "" && sess.Config.UseFIPSEndpoint == endpoints_sdkv1.FIPSEndpointStateEnabled {
		// The SDK doesn't allow setting a custom non-FIPS endpoint *and* enabling UseFIPSEndpoint.
		// However there are a few cases where this is necessary; some services don't have FIPS endpoints,
		// and for some services (e.g. CloudFront) the SDK generates the wrong fips endpoint.
		// While forcing this to disabled may result in the end-user not using a FIPS endpoint as specified
		// by setting UseFIPSEndpoint=true in the provider, the user also explicitly changed the endpoint, so
		// here we need to assume the user knows what they're doing.
		log.Printf("[WARN] UseFIPSEndpoint is enabled but a custom endpoint (%s) is configured, ignoring UseFIPSEndpoint.", endpoint)
		sess.Config.UseFIPSEndpoint = endpoints_sdkv1.FIPSEndpointStateDisabled
	}

	return kms_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
